print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $").strip())
tip = int(input("What percentage tip would you like to give? 10 12 15 ").strip())
people = int(input("How many people to split the bill? ").strip())
total_bill = bill + ((tip / 100) * bill)
print(f"Each person should pay: ${total_bill / people}")
